"""What a pre-built deck *is*, before any of it has been generated.

A template is the deck's structure and nothing else: which words, in what order,
in which lessons, and which sense each one should show. It carries no generated
content, and it deliberately has nowhere to put any — there is no field on
:class:`TemplateWord` in which a source's definition or example sentence could be
pasted.

That is not tidiness, it is the copyright boundary. For a reference collection
like *504 Absolutely Essential Words* the pipeline stores the ordered headword
list and the lesson boundaries, plus a citation; every word of card content is
generated by Vocably or taken from a free dictionary. :class:`TemplateSource`
exists to keep the citation travelling with the deck rather than living in
somebody's memory.

**The order is the product.** For a course, the sequence is the value, so it is
asserted rather than derived: a template declares how many units and words it
expects, and the validator refuses a file that does not match. A word list that
silently lost an entry is otherwise invisible until a learner notices Lesson 12
has eleven words.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from app.domain.entities.deck_build import SenseHint
from app.domain.enums import SenseSelection

#: Strategies a template may name, in the order they will be tried. ``MANUAL``
#: is absent on purpose: it is what an admin's override records, never something
#: a build can choose for itself.
SELECTABLE_STRATEGIES = frozenset(
    {
        SenseSelection.EXPLICIT,
        SenseSelection.HINT,
        SenseSelection.CATEGORY,
        SenseSelection.FIRST,
        SenseSelection.AI,
    }
)

DEFAULT_STRATEGIES: tuple[SenseSelection, ...] = (
    SenseSelection.EXPLICIT,
    SenseSelection.HINT,
    SenseSelection.CATEGORY,
    SenseSelection.FIRST,
)


class TemplateError(ValueError):
    """A template that cannot be built from. Raised before anything is spent."""


@dataclass(frozen=True, slots=True)
class TemplateSource:
    """Where a reference deck's structure came from, and on what terms."""

    title: str = ""
    authors: tuple[str, ...] = ()
    edition: str = ""
    isbn: str = ""
    url: str = ""
    #: Free text stating exactly what was taken and what was not. Written by a
    #: human, kept with the deck, and printed by the validator so that the person
    #: adding a copyrighted list has to look at it.
    rights: str = ""


@dataclass(frozen=True, slots=True)
class GenerationConfig:
    """How this deck's cards should be produced and chosen."""

    native_language: str = "Persian"
    register: str = "adult"
    strategies: tuple[SenseSelection, ...] = DEFAULT_STRATEGIES
    #: Whether a word that exists but lacks the needed sense may be topped up.
    #: Off for decks where any sense will do — every enrichment is a paid call.
    enrichment: bool = True
    max_senses: int = 4


@dataclass(frozen=True, slots=True)
class TemplateWord:
    """One entry of the ordered list."""

    term: str
    hint: SenseHint = field(default_factory=SenseHint)


@dataclass(frozen=True, slots=True)
class TemplateUnit:
    """One lesson/chapter, with its words in the source's order."""

    name: str
    words: tuple[TemplateWord, ...]


@dataclass(frozen=True, slots=True)
class DeckTemplate:
    slug: str
    name: str
    version: str = "1.0.0"
    name_fa: str = ""
    category: str = "general"
    description: str = ""
    description_fa: str = ""
    hue: int = 262
    official: bool = True
    source: TemplateSource = field(default_factory=TemplateSource)
    generation: GenerationConfig = field(default_factory=GenerationConfig)
    units: tuple[TemplateUnit, ...] = ()
    #: sha256 over the raw file bytes. Recorded on the job, so a later diff of
    #: the template shows exactly what a rebuild would change.
    content_hash: str = ""

    @property
    def word_count(self) -> int:
        return sum(len(unit.words) for unit in self.units)

    @property
    def unit_count(self) -> int:
        return len(self.units)

    def words_in_order(self) -> list[tuple[int, TemplateUnit, TemplateWord]]:
        """Every word, flattened, with the unit index it belongs to.

        Flattening here rather than at the call site is what guarantees the deck
        is built in the book's order — the one property a reference deck cannot
        get wrong.
        """
        flat: list[tuple[int, TemplateUnit, TemplateWord]] = []
        for unit_index, unit in enumerate(self.units):
            for word in unit.words:
                flat.append((unit_index, unit, word))
        return flat


@dataclass(frozen=True, slots=True)
class TemplateReport:
    """What validation found. Printed by the CLI before anything is spent."""

    template: DeckTemplate
    #: Terms appearing in more than one place, with where. Not an error: *504*
    #: really does repeat words across lessons, and whether that is a mistake or
    #: two different senses is a judgement only the author can make.
    duplicates: tuple[tuple[str, tuple[str, ...]], ...] = ()
    warnings: tuple[str, ...] = ()

    @property
    def pinned(self) -> int:
        return sum(1 for _, _, word in self.template.words_in_order() if word.hint.is_pinned)

    @property
    def hinted(self) -> int:
        return sum(
            1
            for _, _, word in self.template.words_in_order()
            if word.hint.gloss and not word.hint.is_pinned
        )
